# Generated by Django 3.2.4 on 2021-07-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210708_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='final',
            field=models.CharField(default='fine', max_length=20),
        ),
    ]
