# Generated by Django 3.2.4 on 2021-07-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='final',
        ),
    ]
